use com.mlt.converter.encodings.fsst.FsstEncoder (#53)
This is a quick followup to #52. #52 fixed a lot of decoder tests, but
introduced one build failure:

```
/home/runner/work/maplibre-tile-spec/maplibre-tile-spec/converter/java/src/main/java/com/mlt/vector/fsstdictionary/StringSharedFsstDictionaryVector.java:3: error: package com.fsst does not exist
> Task :compileJava
import com.fsst.FsstEncoder;
               ^
/home/runner/work/maplibre-tile-spec/maplibre-tile-spec/converter/java/src/main/java/com/mlt/vector/fsstdictionary/StringFsstDictionaryVector.java:3: error: package com.fsst does not exist
import com.fsst.FsstEncoder;
```

This fixes the above build failure in order to get the tests running
again.