feat!(rust/mlt): Enable v2 by default (#1860)
While it's still experimental, I think MLT v2 is already at the stage
where ordinary users can try so that they can give feedback before
release. So, I want to make it available with the pre-built binary of
the `mlt` CLI on the GitHub releases. This pull request does it by
enabling `unstable-v2` by default on the mlt crate. (I also want to
enable in mlt-wasm, but I don't address it in this pull request)

This pull request also changes the default of `--mlt-version` to 1 so
that `mlt convert` still generate v1, the latest stable version, by
default. So, this is slightly a breaking change to those who built the
CLI by themselves with `--features unsatable-v2` and run it without
`--mlt-version 2`. For example, these fail without `--mlt-version 2`
specified.

```console
$ mlt convert input.mbtiles output.mbtiles --delta2
Error: the MLT version 2 options in --help only apply to MLT version 2, so they need --mlt-version 2

$ mlt convert input.mbtiles output.mbtiles --tessellate --triangles-only
Error: the MLT version 2 options in --help only apply to MLT version 2, so they need --mlt-version 2
```

Another option might be to specify `--features unsatable-v2` on the CI
build for release. Please let me know if it's better.

AI assistance: Claude (Opus 5.5)